module.exports = {
  mainnet: {
    terra19p20mfnvwh9yvyr7aus3a6z6g6uk28fv4jhx9kmnc2m7krg27q2qkfenjw: {
      protocol: "Orne",
      symbol: "ORNE",
      name: "Orne Token",
      token: "terra19p20mfnvwh9yvyr7aus3a6z6g6uk28fv4jhx9kmnc2m7krg27q2qkfenjw",
      icon: "https://orne.io/img/token_icon.png",
      decimals: 6,
    },
    terra1spkm49wd9dqkranhrks4cupecl3rtgeqqljq3qrvrrts2ev2gw6sy5vz3k: {
      protocol: "portugal.protocol",
      symbol: "Dinheiros",
      name: "dinheiro",
      token: "terra1spkm49wd9dqkranhrks4cupecl3rtgeqqljq3qrvrrts2ev2gw6sy5vz3k",
      icon: "https://static.wixstatic.com/media/1e62a0_04207897171e4f5c8931295172b3e34c~mv2.png",
      decimals: 0,
    },
    terra1sdglum2dt4f3fmq7jrt2phf2tegmnudc7qqqqujkpqcm9ujuxxkqakv5u8: {
      protocol: "portugal.protocol",
      symbol: "Reis",
      name: "real",
      token: "terra1sdglum2dt4f3fmq7jrt2phf2tegmnudc7qqqqujkpqcm9ujuxxkqakv5u8",
      icon: "https://static.wixstatic.com/media/1e62a0_89af25478e5144089de9292b990493e2~mv2.png",
      decimals: 6,
    },
    terra1qj5hs3e86qn4vm9dvtgtlkdp550r0rayk9wpay44mfw3gn3tr8nq5jw3dg: {
      protocol: "portugal.protocol",
      symbol: "Escudos",
      name: "escudo",
      token: "terra1qj5hs3e86qn4vm9dvtgtlkdp550r0rayk9wpay44mfw3gn3tr8nq5jw3dg",
      icon: "https://static.wixstatic.com/media/1e62a0_37bd3a14b88646f987919ec4ea30533c~mv2.png",
      decimals: 6,
    },
    terra13j2k5rfkg0qhk58vz63cze0uze4hwswlrfnm0fa4rnyggjyfrcnqcrs5z2: {
      protocol: "Terra Poker",
      symbol: "TPT",
      name: "Terra Poker Token",
      token: "terra13j2k5rfkg0qhk58vz63cze0uze4hwswlrfnm0fa4rnyggjyfrcnqcrs5z2",
      icon: "https://terra.poker/ico/ms-icon-310x310.png",
      decimals: 6,
    },
    terra1e9s5m6vrl9ms75q0862llq2vcsz8r43czm36s6xnn3vh8dfmwe0s3c86e8: {
      protocol: "Terra Poker",
      symbol: "xTPT",
      name: "Terra Poker Governance Token",
      token: "terra1e9s5m6vrl9ms75q0862llq2vcsz8r43czm36s6xnn3vh8dfmwe0s3c86e8",
      icon: "https://terra.poker/ico/ms-icon-310x310.png",
      decimals: 6,
    },
    terra1cmf8ytutcwrjrv08zskj9phuh46a3w3nkjax7en4hxezsrdr58lqvzy05q: {
      protocol: "alentejo.protocol",
      symbol: "Alem",
      name: "alentejo.money",
      token: "terra1cmf8ytutcwrjrv08zskj9phuh46a3w3nkjax7en4hxezsrdr58lqvzy05q",
      icon: "https://static.wixstatic.com/media/1e62a0_42c272173eb244a893daa63902538ffe~mv2.png/v1/fill/w_560,h_560,fp_0.50_0.50,enc_auto/1e62a0_42c272173eb244a893daa63902538ffe~mv2.png",
      decimals: 6,
    },
    terra14xsm2wzvu7xaf567r693vgfkhmvfs08l68h4tjj5wjgyn5ky8e2qvzyanh: {
      protocol: "Stader",
      symbol: "LunaX",
      name: "LunaX Token",
      token: "terra14xsm2wzvu7xaf567r693vgfkhmvfs08l68h4tjj5wjgyn5ky8e2qvzyanh",
      icon: "https://raw.githubusercontent.com/stader-labs/assets/main/terra/LunaX_1.png",
      decimals: 6,
    },
    terra1ecgazyd0waaj3g7l9cmy5gulhxkps2gmxu9ghducvuypjq68mq2s5lvsct: {
      protocol: "Eris Protocol",
      symbol: "ampLUNA",
      name: "Amplified LUNA",
      token: "terra1ecgazyd0waaj3g7l9cmy5gulhxkps2gmxu9ghducvuypjq68mq2s5lvsct",
      icon: "https://www.erisprotocol.com/assets/ampLuna100.png",
      decimals: 6,
    },
    terra1uv8ltv32tuq4qf6xspytpv058p0pef64s5xdncfywjexv22lfjzs7mul8s:{
      protocol: "Luna Bird Board",
      symbol: "LUBI",
      name: "Luna Bird Token",
      token: "terra1uv8ltv32tuq4qf6xspytpv058p0pef64s5xdncfywjexv22lfjzs7mul8s",
      icon: "https://www.lunabird.network/logo.png",
      decimals: 6,
    },
    terra1xumzh893lfa7ak5qvpwmnle5m5xp47t3suwwa9s0ydqa8d8s5faqn6x7al: {
      protocol: "STEAK Protocol",
      name: "STEAK Liquid Token",
      symbol: "STEAK",
      token: "terra1xumzh893lfa7ak5qvpwmnle5m5xp47t3suwwa9s0ydqa8d8s5faqn6x7al",
      icon: "https://liquidstaking.app/steak.png",
    },
    terra1nsuqsk6kh58ulczatwev87ttq2z6r3pusulg9r24mfj2fvtzd4uq3exn26: {
      protocol: "Astroport",
      symbol: "ASTRO",
      name: "Astroport Token",
      token: "terra1nsuqsk6kh58ulczatwev87ttq2z6r3pusulg9r24mfj2fvtzd4uq3exn26",
      icon: "https://astroport.fi/astro_logo.png",
      decimals: 6,
    },
     terra1x62mjnme4y0rdnag3r8rfgjuutsqlkkyuh4ndgex0wl3wue25uksau39q8: {
      protocol: "Astroport",
      symbol: "xASTRO",
      name: "Staked Astroport Token",
      token: "terra1x62mjnme4y0rdnag3r8rfgjuutsqlkkyuh4ndgex0wl3wue25uksau39q8",
      icon: "https://app.astroport.fi/tokens/xAstro.png",
      decimals: 6,
    },
     terra15hhqg8gyz04zapynqtk7uvlsp7lzay7etrt9ann0276v94yae63sxygeat: {
      protocol: "Wormhole",
      symbol: "wETH",
      name: "Wrapped Ether (Portal)",
      token: "terra15hhqg8gyz04zapynqtk7uvlsp7lzay7etrt9ann0276v94yae63sxygeat",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs/logo.png",
      decimals: 8,
    },
    terra1ctelwayk6t2zu30a8v9kdg3u2gr0slpjdfny5pjp7m3tuquk32ysugyjdg: {
      protocol: "Wormhole",
      symbol: "wSOL",
      name: "Wrapped SOL",
      token: "terra1ctelwayk6t2zu30a8v9kdg3u2gr0slpjdfny5pjp7m3tuquk32ysugyjdg",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png",
      decimals: 8,
    },
    terra1qmnxhecc3vnmhef9q7vap7spx9tgpnw9fqe8ljqfwrlz7rur9y5qu2dlp6: {
      protocol: "Wormhole",
      symbol: "wAVAX",
      name: "AVAX (Portal)",
      token: "terra1qmnxhecc3vnmhef9q7vap7spx9tgpnw9fqe8ljqfwrlz7rur9y5qu2dlp6",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/AVAX_wh.png",
      decimals: 8,
    },
     terra1564y9uxzhast8sk5n47teypy4mxy7fg5vne2msuztsft7qk3pj9sxxuxmc: {
      protocol: "TerraFloki",
      symbol: "TFLOKI",
      name: "TerraFloki Token",
      token: "terra1564y9uxzhast8sk5n47teypy4mxy7fg5vne2msuztsft7qk3pj9sxxuxmc",
      icon: "https://terrafloki.io/tf-logo.png",
    },
    terra1gy73st560m2j0esw5c5rjmr899hvtv4rhh4seeajt3clfhr4aupszjss4j: {
      protocol: "ValkyrieProtocol",
      symbol: "VKR",
      name: "VKR Token",
      token: "terra1gy73st560m2j0esw5c5rjmr899hvtv4rhh4seeajt3clfhr4aupszjss4j",
      icon: "https://app.valkyrieprotocol.com/icon_vkr.png",
      decimals: 6,
    },
    terra1ee4g63c3sus9hnyyp3p2u3tulzdv5ag68l55q8ej64y4qpwswvus5mtag2: {
      protocol: "Lira",
      symbol: "LIRA",
      name: "Lira Token",
      token: "terra1ee4g63c3sus9hnyyp3p2u3tulzdv5ag68l55q8ej64y4qpwswvus5mtag2",
      icon: "https://lira.financial/images/icons/lira.svg",
      decimals: 6,
    },
    terra1ttspm8jgeylc6us3mlpwpmlwzr3rkesm70vn6zkfr07pz7e3rzkq73ah2j: {
      protocol: "Gidorah",
      symbol: "GIDO",
      name: "Gidorah",
      token: "terra1ttspm8jgeylc6us3mlpwpmlwzr3rkesm70vn6zkfr07pz7e3rzkq73ah2j",
      icon: "https://firebasestorage.googleapis.com/v0/b/wicca-c3bbe.appspot.com/o/app%2Fmainnet%2Ftoken%2FMIRhzK1keYKtJsRYg_oL9.jpeg?alt=media&token=5de0205f-d0f6-4a76-b765-e6dd59d7d47a",
    },
    terra1xe8umegahlqphtpvjsuwfzfvyjfvag5h8rffsx6ezm0el4xzsf8s7uzezk: {
      protocol: "Redacted.money",
      symbol: "RED",
      name: "Red",
      token: "terra1xe8umegahlqphtpvjsuwfzfvyjfvag5h8rffsx6ezm0el4xzsf8s7uzezk",
      icon: "https://red.redacted.money/red.svg",
    },
    terra1l23rtnsp0fcfgs2zlww4gcd8dlznkm580p5yrsangcen9jjjhuqstd2sle: {
        protocol: "Stader",
        symbol: "SD",
        name: "SD Token",
        token: "terra1l23rtnsp0fcfgs2zlww4gcd8dlznkm580p5yrsangcen9jjjhuqstd2sle",
        icon: "https://raw.githubusercontent.com/stader-labs/assets/main/terra/SD_Token.png",
        decimals: 8,
      },
    terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml: {
      protocol: "boneLuna",
      symbol: "bLUNA",
      name: "boneLuna",
      token: "terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml",
      icon: "https://gravedigger.backbonelabs.io/boneluna.png",
      decimals: 6
    },
    terra17gck626vgax9jpe6utm7dhx4vdzawfkt0jhru03l7a3dzu98wedsfad4sz: {
      protocol: "Depeg Nation",
      symbol: "dUST",
      name: "Depegged UST",
      token: "terra17gck626vgax9jpe6utm7dhx4vdzawfkt0jhru03l7a3dzu98wedsfad4sz",
      icon: "https://gateway.pinata.cloud/ipfs/QmTEo7AmbgygF2mek89MHBJ1wPrB23TA811VeXCdcXW5pf",
      decimals: 6
    },
    terra1d4j9lsl453mkvtlg4ctw8y52rdkhafsaefug0hq0z06phczuvvvs7uq0vg: {
      protocol: "INTERCHAIN DAO COIN",
      symbol: "IDC",
      name: "INTERCHAIN DAO COIN",
      token: "terra1d4j9lsl453mkvtlg4ctw8y52rdkhafsaefug0hq0z06phczuvvvs7uq0vg",
      icon: "https://raw.githubusercontent.com/IDC1201/IDC/f22b0f203867414b6473f8e8a935c3edf5524296/ASSET/IDC.png",
      decimals: 6
    },
    terra1qx284aak0wl7vrvlsc6cwcsn6xwajragkh6cjqj87m9p34hx5l2s22p3cp: {
      protocol: "Tuna Money",
      symbol: "TUNA",
      name: "Tuna Token",
      token: "terra1qx284aak0wl7vrvlsc6cwcsn6xwajragkh6cjqj87m9p34hx5l2s22p3cp",
      icon: "https://s3.ap-southeast-2.wasabisys.com/tuna/tunatoken.png",
      decimals: 6
    },
      terra1kkpf3f049trkyscv0av2pa9ad02dzls7f6m8s24q07ehetggytesru7qqp: {
      protocol: "Brand Governance Network",
      symbol: "BGT",
      name: "Brand Governance Token",
      token: "terra1kkpf3f049trkyscv0av2pa9ad02dzls7f6m8s24q07ehetggytesru7qqp",
      icon: "https://s3.ap-southeast-2.wasabisys.com/bgt/bgtoken.png",
      decimals: 6
    },
    terra1q8kfp0v9rhef0d3u44ds9shwvwcusjheh8nhye3n7gwjd95ze96sehyp6w: {
      protocol: "Santerra",
      symbol: "SANT",
      name: "SANTERRA SANT Token",
      token: "terra1q8kfp0v9rhef0d3u44ds9shwvwcusjheh8nhye3n7gwjd95ze96sehyp6w",
      icon: "https://santerra.app/sant_logo.svg",
      decimals: 6
    },
  },
  classic: {
    terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp: {
      protocol: "Anchor",
      symbol: "bLuna",
      token: "terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp",
      icon: "https://whitelist.anchorprotocol.com/logo/bLUNA.png",
    },
    terra1dzhzukyezv0etz22ud940z7adyv7xgcjkahuun: {
      protocol: "Anchor",
      symbol: "bETH",
      token: "terra1dzhzukyezv0etz22ud940z7adyv7xgcjkahuun",
      icon: "https://whitelist.anchorprotocol.com/logo/bETH.png",
    },
    terra1hzh9vpxhsk8253se0vv5jj6etdvxu3nv8z07zu: {
      protocol: "Anchor",
      symbol: "aUST",
      token: "terra1hzh9vpxhsk8253se0vv5jj6etdvxu3nv8z07zu",
      icon: "https://whitelist.anchorprotocol.com/logo/aUST.png",
    },
    terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76: {
      protocol: "Anchor",
      symbol: "ANC",
      token: "terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76",
      icon: "https://whitelist.anchorprotocol.com/logo/ANC.png",
    },
    terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6: {
      protocol: "Mirror",
      symbol: "MIR",
      name: "Mirror",
      token: "terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6",
      icon: "https://whitelist.mirror.finance/icon/MIR.png",
    },
    terra1vxtwu4ehgzz77mnfwrntyrmgl64qjs75mpwqaz: {
      protocol: "Mirror",
      symbol: "mAAPL",
      name: "Apple Inc.",
      token: "terra1vxtwu4ehgzz77mnfwrntyrmgl64qjs75mpwqaz",
      icon: "https://whitelist.mirror.finance/icon/AAPL.png",
    },
    terra1g4x2pzmkc9z3mseewxf758rllg08z3797xly0n: {
      protocol: "Mirror",
      symbol: "mABNB",
      name: "Airbnb Inc.",
      token: "terra1g4x2pzmkc9z3mseewxf758rllg08z3797xly0n",
      icon: "https://whitelist.mirror.finance/icon/ABNB.png",
    },
    terra1qelfthdanju7wavc5tq0k5r0rhsyzyyrsn09qy: {
      protocol: "Mirror",
      symbol: "mAMC (Delisted)",
      name: "AMC Entertainment Holdings Inc.",
      token: "terra1qelfthdanju7wavc5tq0k5r0rhsyzyyrsn09qy",
      icon: "https://whitelist.mirror.finance/icon/AMC.png",
    },
    terra18ej5nsuu867fkx4tuy2aglpvqjrkcrjjslap3z: {
      protocol: "Mirror",
      symbol: "mAMD",
      name: "Advanced Micro Devices, Inc.",
      token: "terra18ej5nsuu867fkx4tuy2aglpvqjrkcrjjslap3z",
      icon: "https://whitelist.mirror.finance/icon/AMD.png",
    },
    terra165nd2qmrtszehcfrntlplzern7zl4ahtlhd5t2: {
      protocol: "Mirror",
      symbol: "mAMZN",
      name: "Amazon.com, Inc.",
      token: "terra165nd2qmrtszehcfrntlplzern7zl4ahtlhd5t2",
      icon: "https://whitelist.mirror.finance/icon/AMZN.png",
    },
    terra1qqfx5jph0rsmkur2zgzyqnfucra45rtjae5vh6: {
      protocol: "Mirror",
      symbol: "mARKK",
      name: "ARK Innovation ETF",
      token: "terra1qqfx5jph0rsmkur2zgzyqnfucra45rtjae5vh6",
      icon: "https://whitelist.mirror.finance/icon/ARKK.png",
    },
    terra1w7zgkcyt7y4zpct9dw8mw362ywvdlydnum2awa: {
      protocol: "Mirror",
      symbol: "mBABA",
      name: "Alibaba Group Holding Limited",
      token: "terra1w7zgkcyt7y4zpct9dw8mw362ywvdlydnum2awa",
      icon: "https://whitelist.mirror.finance/icon/BABA.png",
    },
    terra1rhhvx8nzfrx5fufkuft06q5marfkucdqwq5sjw: {
      protocol: "Mirror",
      symbol: "mBTC",
      name: "Bitcoin",
      token: "terra1rhhvx8nzfrx5fufkuft06q5marfkucdqwq5sjw",
      icon: "https://whitelist.mirror.finance/icon/BTC.png",
    },
    terra18wayjpyq28gd970qzgjfmsjj7dmgdk039duhph: {
      protocol: "Mirror",
      symbol: "mCOIN",
      name: "Coinbase Global, Inc.",
      token: "terra18wayjpyq28gd970qzgjfmsjj7dmgdk039duhph",
      icon: "https://whitelist.mirror.finance/icon/COIN.png",
    },
    terra149755r3y0rve30e209awkhn5cxgkn5c8ju9pm5: {
      protocol: "Mirror",
      symbol: "mDIS",
      name: "The Walt Disney Company",
      token: "terra149755r3y0rve30e209awkhn5cxgkn5c8ju9pm5",
      icon: "https://whitelist.mirror.finance/icon/DIS.png",
    },
    terra19ya4jpvjvvtggepvmmj6ftmwly3p7way0tt08r: {
      protocol: "Mirror",
      symbol: "mDOT",
      name: "Polkadot",
      token: "terra19ya4jpvjvvtggepvmmj6ftmwly3p7way0tt08r",
      icon: "https://whitelist.mirror.finance/icon/DOT.png",
    },
    terra1dk3g53js3034x4v5c3vavhj2738une880yu6kx: {
      protocol: "Mirror",
      symbol: "mETH",
      name: "Ether",
      token: "terra1dk3g53js3034x4v5c3vavhj2738une880yu6kx",
      icon: "https://whitelist.mirror.finance/icon/ETH.png",
    },
    terra1mqsjugsugfprn3cvgxsrr8akkvdxv2pzc74us7: {
      protocol: "Mirror",
      symbol: "mFB",
      name: "Facebook Inc.",
      token: "terra1mqsjugsugfprn3cvgxsrr8akkvdxv2pzc74us7",
      icon: "https://whitelist.mirror.finance/icon/FB.png",
    },
    terra1l5lrxtwd98ylfy09fn866au6dp76gu8ywnudls: {
      protocol: "Mirror",
      symbol: "mGLXY",
      name: "Galaxy Digital Holdings Ltd",
      token: "terra1l5lrxtwd98ylfy09fn866au6dp76gu8ywnudls",
      icon: "https://whitelist.mirror.finance/icon/GLXY.png",
    },
    terra1m6j6j9gw728n82k78s0j9kq8l5p6ne0xcc820p: {
      protocol: "Mirror",
      symbol: "mGME (Delisted)",
      name: "GameStop Corp",
      token: "terra1m6j6j9gw728n82k78s0j9kq8l5p6ne0xcc820p",
      icon: "https://whitelist.mirror.finance/icon/GME.png",
    },
    terra1h8arz2k547uvmpxctuwush3jzc8fun4s96qgwt: {
      protocol: "Mirror",
      symbol: "mGOOGL",
      name: "Alphabet Inc.",
      token: "terra1h8arz2k547uvmpxctuwush3jzc8fun4s96qgwt",
      icon: "https://whitelist.mirror.finance/icon/GOOGL.png",
    },
    terra137drsu8gce5thf6jr5mxlfghw36rpljt3zj73v: {
      protocol: "Mirror",
      symbol: "mGS",
      name: "Goldman Sachs Group Inc.",
      token: "terra137drsu8gce5thf6jr5mxlfghw36rpljt3zj73v",
      icon: "https://whitelist.mirror.finance/icon/GS.png",
    },
    terra18yqdfzfhnguerz9du5mnvxsh5kxlknqhcxzjfr: {
      protocol: "Mirror",
      symbol: "mHOOD",
      name: "Robinhood Markets, Inc.",
      token: "terra18yqdfzfhnguerz9du5mnvxsh5kxlknqhcxzjfr",
      icon: "https://whitelist.mirror.finance/icon/HOOD.png",
    },
    terra10h7ry7apm55h4ez502dqdv9gr53juu85nkd4aq: {
      protocol: "Mirror",
      symbol: "mIAU",
      name: "iShares Gold Trust",
      token: "terra10h7ry7apm55h4ez502dqdv9gr53juu85nkd4aq",
      icon: "https://whitelist.mirror.finance/icon/IAU.png",
    },
    terra15hp9pr8y4qsvqvxf3m4xeptlk7l8h60634gqec: {
      protocol: "Mirror",
      symbol: "mIAU (Delisted)",
      name: "iShares Gold Trust",
      token: "terra15hp9pr8y4qsvqvxf3m4xeptlk7l8h60634gqec",
      icon: "https://whitelist.mirror.finance/icon/IAU.png",
    },
    terra1ptdxmj3xmmljzx02nr4auwfuelmj0cnkh8egs2: {
      protocol: "Mirror",
      symbol: "mJNJ",
      name: "Johnson & Johnson",
      token: "terra1ptdxmj3xmmljzx02nr4auwfuelmj0cnkh8egs2",
      icon: "https://whitelist.mirror.finance/icon/JNJ.png",
    },
    terra1qsnj5gvq8rgs7yws8x5u02gwd5wvtu4tks0hjm: {
      protocol: "Mirror",
      symbol: "mKO",
      name: "Coca-Cola",
      token: "terra1qsnj5gvq8rgs7yws8x5u02gwd5wvtu4tks0hjm",
      icon: "https://whitelist.mirror.finance/icon/KO.png",
    },
    terra1227ppwxxj3jxz8cfgq00jgnxqcny7ryenvkwj6: {
      protocol: "Mirror",
      symbol: "mMSFT",
      name: "Microsoft Corporation",
      token: "terra1227ppwxxj3jxz8cfgq00jgnxqcny7ryenvkwj6",
      icon: "https://whitelist.mirror.finance/icon/MSFT.png",
    },
    terra1jsxngqasf2zynj5kyh0tgq9mj3zksa5gk35j4k: {
      protocol: "Mirror",
      symbol: "mNFLX",
      name: "Netflix, Inc.",
      token: "terra1jsxngqasf2zynj5kyh0tgq9mj3zksa5gk35j4k",
      icon: "https://whitelist.mirror.finance/icon/NFLX.png",
    },
    terra1dj2cj02zak0nvwy3uj9r9dhhxhdwxnw6psse6p: {
      protocol: "Mirror",
      symbol: "mNIO",
      name: "NIO Inc.",
      token: "terra1dj2cj02zak0nvwy3uj9r9dhhxhdwxnw6psse6p",
      icon: "https://whitelist.mirror.finance/icon/NIO.png",
    },
    terra17ana8hvzea0q7w367dm0dw48sxwql39qekpt7g: {
      protocol: "Mirror",
      symbol: "mNKE",
      name: "NIKE, Inc.",
      token: "terra17ana8hvzea0q7w367dm0dw48sxwql39qekpt7g",
      icon: "https://whitelist.mirror.finance/icon/NKE.png",
    },
    terra1drsjzvzej4h4qlehcfwclxg4w5l3h5tuvd3jd8: {
      protocol: "Mirror",
      symbol: "mNVDA",
      name: "NVIDIA Corporation",
      token: "terra1drsjzvzej4h4qlehcfwclxg4w5l3h5tuvd3jd8",
      icon: "https://whitelist.mirror.finance/icon/NVDA.png",
    },
    terra1rh2907984nudl7vh56qjdtvv7947z4dujj92sx: {
      protocol: "Mirror",
      symbol: "mPYPL",
      name: "PayPal Holdings Inc",
      token: "terra1rh2907984nudl7vh56qjdtvv7947z4dujj92sx",
      icon: "https://whitelist.mirror.finance/icon/PYPL.png",
    },
    terra1csk6tc7pdmpr782w527hwhez6gfv632tyf72cp: {
      protocol: "Mirror",
      symbol: "mQQQ",
      name: "Invesco QQQ Trust",
      token: "terra1csk6tc7pdmpr782w527hwhez6gfv632tyf72cp",
      icon: "https://whitelist.mirror.finance/icon/QQQ.png",
    },
    terra1246zy658dfgtausf0c4a6ly8sc2e285q4kxqga: {
      protocol: "Mirror",
      symbol: "mSBUX",
      name: "Starbucks Corporation",
      token: "terra1246zy658dfgtausf0c4a6ly8sc2e285q4kxqga",
      icon: "https://whitelist.mirror.finance/icon/SBUX.png",
    },
    terra1kscs6uhrqwy6rx5kuw5lwpuqvm3t6j2d6uf2lp: {
      protocol: "Mirror",
      symbol: "mSLV",
      name: "iShares Silver Trust",
      token: "terra1kscs6uhrqwy6rx5kuw5lwpuqvm3t6j2d6uf2lp",
      icon: "https://whitelist.mirror.finance/icon/SLV.png",
    },
    terra1aa00lpfexyycedfg5k2p60l9djcmw0ue5l8fhc: {
      protocol: "Mirror",
      symbol: "mSPY",
      name: "SPDR S&P 500",
      token: "terra1aa00lpfexyycedfg5k2p60l9djcmw0ue5l8fhc",
      icon: "https://whitelist.mirror.finance/icon/SPY.png",
    },
    terra1u43zu5amjlsgty5j64445fr9yglhm53m576ugh: {
      protocol: "Mirror",
      symbol: "mSQ",
      name: "Square, Inc.",
      token: "terra1u43zu5amjlsgty5j64445fr9yglhm53m576ugh",
      icon: "https://whitelist.mirror.finance/icon/SQ.png",
    },
    terra14y5affaarufk3uscy2vr6pe6w6zqf2wpjzn5sh: {
      protocol: "Mirror",
      symbol: "mTSLA",
      name: "Tesla, Inc.",
      token: "terra14y5affaarufk3uscy2vr6pe6w6zqf2wpjzn5sh",
      icon: "https://whitelist.mirror.finance/icon/TSLA.png",
    },
    terra1cc3enj9qgchlrj34cnzhwuclc4vl2z3jl7tkqg: {
      protocol: "Mirror",
      symbol: "mTWTR",
      name: "Twitter, Inc.",
      token: "terra1cc3enj9qgchlrj34cnzhwuclc4vl2z3jl7tkqg",
      icon: "https://whitelist.mirror.finance/icon/TWTR.png",
    },
    terra1lvmx8fsagy70tv0fhmfzdw9h6s3sy4prz38ugf: {
      protocol: "Mirror",
      symbol: "mUSO",
      name: "United States Oil Fund, LP",
      token: "terra1lvmx8fsagy70tv0fhmfzdw9h6s3sy4prz38ugf",
      icon: "https://whitelist.mirror.finance/icon/USO.png",
    },
    terra19cmt6vzvhnnnfsmccaaxzy2uaj06zjktu6yzjx: {
      protocol: "Mirror",
      symbol: "mVIXY",
      name: "ProShares VIX Short-Term Futures ETF",
      token: "terra19cmt6vzvhnnnfsmccaaxzy2uaj06zjktu6yzjx",
      icon: "https://whitelist.mirror.finance/icon/VIXY.png",
    },
    terra1zp3a6q6q4953cz376906g5qfmxnlg77hx3te45: {
      protocol: "Mirror",
      symbol: "mVIXY (Delisted)",
      name: "ProShares VIX Short-Term Futures ETF",
      token: "terra1zp3a6q6q4953cz376906g5qfmxnlg77hx3te45",
      icon: "https://whitelist.mirror.finance/icon/VIXY.png",
    },
    terra1ez46kxtulsdv07538fh5ra5xj8l68mu8eg24vr: {
      protocol: "LoTerra",
      symbol: "LOTA",
      token: "terra1ez46kxtulsdv07538fh5ra5xj8l68mu8eg24vr",
      icon: "https://loterra.io/LOTA.png",
    },
    terra17jnhankdfl8vyzj6vejt7ag8uz0cjc9crkl2h7: {
      protocol: "Digipharm",
      symbol: "DPH",
      name: "Digipharm",
      token: "terra17jnhankdfl8vyzj6vejt7ag8uz0cjc9crkl2h7",
      icon: "https://digipharm.io/wp-content/uploads/2021/02/digipharm_etherscan_logo.png",
    },
    terra1kcthelkax4j9x8d3ny6sdag0qmxxynl3qtcrpy: {
      protocol: "Pylon",
      symbol: "MINE",
      name: "Pylon MINE Token",
      token: "terra1kcthelkax4j9x8d3ny6sdag0qmxxynl3qtcrpy",
      icon: "https://assets.pylon.rocks/logo/MINE.png",
    },
    terra1zsaswh926ey8qa5x4vj93kzzlfnef0pstuca0y: {
      protocol: "Pylon",
      symbol: "bPsiDP-24m",
      name: "Pylon bDP Token for Gateway Psi 24m Pool",
      token: "terra1zsaswh926ey8qa5x4vj93kzzlfnef0pstuca0y",
      icon: "https://assets.pylon.rocks/logo/bPsiDP.png",
    },
    terra1s5eczhe0h0jutf46re52x5z4r03c8hupacxmdr: {
      protocol: "Spectrum",
      symbol: "SPEC",
      name: "Spectrum Token",
      token: "terra1s5eczhe0h0jutf46re52x5z4r03c8hupacxmdr",
      icon: "https://terra.spec.finance/assets/SPEC.png",
    },
    terra1nef5jf6c7js9x6gkntlehgywvjlpytm7pcgkn4: {
      protocol: "LOOP",
      symbol: "LOOPC",
      name: "LOOPC token",
      token: "terra1nef5jf6c7js9x6gkntlehgywvjlpytm7pcgkn4",
      icon: "https://dex.loop.markets/loopc.png",
    },
    terra1jx4lmmke2srcvpjeereetc9hgegp4g5j0p9r2q: {
      protocol: "LOOP",
      symbol: "LOOPRC",
      name: "LOOPRC token",
      token: "terra1jx4lmmke2srcvpjeereetc9hgegp4g5j0p9r2q",
      icon: "https://dex.loop.markets/looprc.png",
    },
    terra13xujxcrc9dqft4p9a8ls0w3j0xnzm6y2uvve8n: {
      protocol: "StarTerra",
      symbol: "STT",
      name: "StarTerra Token",
      token: "terra13xujxcrc9dqft4p9a8ls0w3j0xnzm6y2uvve8n",
      icon: "https://starterra.io/assets/100x100_starterra.png",
    },
    terra19djkaepjjswucys4npd5ltaxgsntl7jf0xz7w6: {
      protocol: "TerraWorld",
      symbol: "TWD",
      name: "TWD Token",
      token: "terra19djkaepjjswucys4npd5ltaxgsntl7jf0xz7w6",
      icon: "https://terraoffice.world/twd_logo.png",
    },
    terra1kvjscdgwuvwc6uzm4rqfjl6nlmuhj28tequlnc: {
      protocol: "TerraWorld",
      symbol: "XTRA",
      name: "xterra Token",
      token: "terra1kvjscdgwuvwc6uzm4rqfjl6nlmuhj28tequlnc",
      icon: "https://terraworld.me/assets/XTRA.png",
    },
    terra1vtr50tw0pgqpes34zqu60n554p9x4950wk8f63: {
      protocol: "Miaw Trader",
      symbol: "MIAW",
      name: "MIAW Token",
      token: "terra1vtr50tw0pgqpes34zqu60n554p9x4950wk8f63",
      icon: "https://www.miaw-trader.com/logo.png",
    },
    terra12897djskt9rge8dtmm86w654g7kzckkd698608: {
      protocol: "Nexus",
      symbol: "Psi",
      name: "Nexus Governance Token",
      token: "terra12897djskt9rge8dtmm86w654g7kzckkd698608",
      icon: "https://terra.nexusprotocol.app/assets/psi.png",
      decimals: 6,
    },
    terra10f2mt82kjnkxqj2gepgwl637u2w4ue2z5nhz5j: {
      protocol: "Nexus",
      symbol: "nLuna",
      name: "Nexus nLuna Token",
      token: "terra10f2mt82kjnkxqj2gepgwl637u2w4ue2z5nhz5j",
      icon: "https://terra.nexusprotocol.app/nLuna.svg",
      decimals: 6,
    },
    terra178v546c407pdnx5rer3hu8s2c0fc924k74ymnn: {
      protocol: "Nexus",
      symbol: "nETH",
      name: "Nexus nETH Token",
      token: "terra178v546c407pdnx5rer3hu8s2c0fc924k74ymnn",
      icon: "https://terra.nexusprotocol.app/nEth.svg",
      decimals: 6,
    },
    terra1u553zk43jd4rwzc53qrdrq4jc2p8rextyq09dj: {
      protocol: "Nexus",
      symbol: "cnLuna",
      name: "nLuna autocompounder share representation",
      token: "terra1u553zk43jd4rwzc53qrdrq4jc2p8rextyq09dj",
      icon: "https://terra.nexusprotocol.app/cnLuna.svg",
      decimals: 6,
    },
    terra1nagqpmyw55yjphea4rhntlfv87ugmeaj8ym756: {
      protocol: "Nexus",
      symbol: "cnETH",
      name: "nETH autocompounder share representation",
      token: "terra1nagqpmyw55yjphea4rhntlfv87ugmeaj8ym756",
      icon: "https://terra.nexusprotocol.app/cnETH.svg",
      decimals: 6,
    },
    terra13k62n0285wj8ug0ngcgpf7dgnkzqeu279tz636: {
      protocol: "Nexus",
      symbol: "nAVAX",
      name: "Nexus nAVAX Token",
      token: "terra13k62n0285wj8ug0ngcgpf7dgnkzqeu279tz636",
      icon: "https://terra.nexusprotocol.app/nAVAX.svg",
      decimals: 6,
    },
    terra1jtdc6zpf95tvh9peuaxwp3v0yqszcnwl8j5ade: {
      protocol: "Nexus",
      symbol: "nATOM",
      name: "Nexus nATOM Token",
      token: "terra1jtdc6zpf95tvh9peuaxwp3v0yqszcnwl8j5ade",
      icon: "https://terra.nexusprotocol.app/nATOM.svg",
      decimals: 6,
    },
    terra1dy9kmlm4anr92e42mrkjwzyvfqwz66un00rwr5: {
      protocol: "ValkyrieProtocol",
      symbol: "VKRC",
      name: "VKRC Token",
      token: "terra1dy9kmlm4anr92e42mrkjwzyvfqwz66un00rwr5",
      icon: "https://classic-app.valkyrieprotocol.com/icon_vkr.png",
    },
    terra1mddcdx0ujx89f38gu7zspk2r2ffdl5enyz2u03: {
      protocol: "Orion Money",
      symbol: "ORION",
      name: "Orion Money (Portal)",
      token: "terra1mddcdx0ujx89f38gu7zspk2r2ffdl5enyz2u03",
      icon: "https://orion.money/assets/ORION-LOGO-2.1-GREEN@256x256.png",
      decimals: 8,
    },
    terra1r5506ckw5tfr3z52jwlek8vg9sn3yflrqrzfsc: {
      protocol: "TerraLand",
      symbol: "TLAND",
      name: "TerraLand Token",
      token: "terra1r5506ckw5tfr3z52jwlek8vg9sn3yflrqrzfsc",
      icon: "https://terralandio-site.s3.eu-central-1.amazonaws.com/TerraLand-logo-v1c-4x.png",
      decimals: 6,
    },
    terra1php5m8a6qd68z02t3zpw4jv2pj4vgw4wz0t8mz: {
      protocol: "White Whale",
      symbol: "WHALE",
      name: "Whale Token",
      token: "terra1php5m8a6qd68z02t3zpw4jv2pj4vgw4wz0t8mz",
      icon: "https://www.whitewhale.money/tokenlogo.png",
      decimals: 6,
    },
    terra1w0p5zre38ecdy3ez8efd5h9fvgum5s206xknrg: {
      protocol: "White Whale",
      symbol: "vUST",
      name: "Vault UST",
      token: "terra1w0p5zre38ecdy3ez8efd5h9fvgum5s206xknrg",
      icon: "https://www.whitewhale.money/vustlogo.png",
      decimals: 6,
    },
    terra14tl83xcwqjy0ken9peu4pjjuu755lrry2uy25r: {
      protocol: "Wormhole",
      symbol: "ETH",
      name: "Ether (Portal)",
      token: "terra14tl83xcwqjy0ken9peu4pjjuu755lrry2uy25r",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs/logo.png",
      decimals: 8,
    },
    terra1aa7upykmmqqc63l924l5qfap8mrmx5rfdm0v55: {
      protocol: "Wormhole",
      symbol: "WBTC",
      name: "Wrapped BTC (Portal)",
      token: "terra1aa7upykmmqqc63l924l5qfap8mrmx5rfdm0v55",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh/logo.png",
      decimals: 8,
    },
    terra190tqwgqx7s8qrknz6kckct7v607cu068gfujpk: {
      protocol: "Wormhole",
      symbol: "SOL",
      name: "SOL (Portal)",
      token: "terra190tqwgqx7s8qrknz6kckct7v607cu068gfujpk",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png",
      decimals: 8,
    },
    terra1dfasranqm4uyaz72r960umxy0w8t6zewqlnkuq: {
      protocol: "Wormhole",
      symbol: "MATICet",
      name: "MATIC (Portal from Ethereum)",
      token: "terra1dfasranqm4uyaz72r960umxy0w8t6zewqlnkuq",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/C7NNPWuZCNjZBfW5p6JvGsR8pUdsRpEdP1ZAhnoDwj7h/logo.png",
      decimals: 8,
    },
    terra1cetg5wruw2wsdjp7j46rj44xdel00z006e9yg8: {
      protocol: "Wormhole",
      symbol: "BNB",
      name: "Binance Coin (Portal)",
      token: "terra1cetg5wruw2wsdjp7j46rj44xdel00z006e9yg8",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9gP2kCy3wA1ctvYWQk75guqXuHfrEomqydHLtcTCqiLa/logo.png",
      decimals: 8,
    },
    terra1xvqlpjl2dxyel9qrp6qvtrg04xe3jh9cyxc6av: {
      protocol: "Wormhole",
      symbol: "CAKE",
      name: "PancakeSwap Token (Portal)",
      token: "terra1xvqlpjl2dxyel9qrp6qvtrg04xe3jh9cyxc6av",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/J8LKx7pr9Zxh9nMhhT7X3EBmj5RzuhFrHKyJAe2F2i9S/logo.png",
      decimals: 8,
    },
    terra12dfv3f0e6m22z6cnhfn3nxk2en3z3zeqy6ctym: {
      protocol: "Wormhole",
      symbol: "LINK",
      name: "Chainlink (Portal)",
      token: "terra12dfv3f0e6m22z6cnhfn3nxk2en3z3zeqy6ctym",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/2wpTofQ8SkACrkZWrZDjXPitYa8AwWgX8AfxdeBRRVLX/logo.png",
      decimals: 8,
    },
    terra1csvuzlf92nyemu6tv25h0l79etpe8hz3h5vn4a: {
      protocol: "Wormhole",
      symbol: "SUSHI",
      name: "SushiToken (Portal)",
      token: "terra1csvuzlf92nyemu6tv25h0l79etpe8hz3h5vn4a",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/ChVzxWRmrTeSgwd3Ui3UumcN8KX7VK3WaD4KGeSKpypj/logo.png",
      decimals: 8,
    },
    terra1wyxkuy5jq545fn7xfn3enpvs5zg9f9dghf6gxf: {
      protocol: "Wormhole",
      symbol: "UNI",
      name: "Uniswap (Portal)",
      token: "terra1wyxkuy5jq545fn7xfn3enpvs5zg9f9dghf6gxf",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/8FU95xFJhUUkyyCLU13HSzDLs7oC4QZdXQHL6SCeab36/logo.png",
      decimals: 8,
    },
    terra1ce06wkrdm4vl6t0hvc0g86rsy27pu8yadg3dva: {
      protocol: "Wormhole",
      symbol: "USDTet",
      name: "Tether USD (Portal from Ethereum)",
      token: "terra1ce06wkrdm4vl6t0hvc0g86rsy27pu8yadg3dva",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Dn4noZ5jgGfkntzcQSUZ8czkreiZ1ForXYoV2H8Dm7S1/logo.png",
      decimals: 6,
    },
    terra1pepwcav40nvj3kh60qqgrk8k07ydmc00xyat06: {
      protocol: "Wormhole",
      symbol: "USDCet",
      name: "USD Coin (Portal from Ethereum)",
      token: "terra1pepwcav40nvj3kh60qqgrk8k07ydmc00xyat06",
      icon: "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/A9mUU4qviSctJVPJdBJWkb28deg915LYJKrzQ19ji3FM/logo.png",
      decimals: 6,
    },
    terra1xfsdgcemqwxp4hhnyk4rle6wr22sseq7j07dnn: {
      protocol: "Kujira",
      symbol: "KUJI",
      name: "Kujira Token",
      token: "terra1xfsdgcemqwxp4hhnyk4rle6wr22sseq7j07dnn",
      icon: "https://assets.kujira.app/kuji.png",
      decimals: 6,
    },
    terra188w26t95tf4dz77raftme8p75rggatxjxfeknw: {
      protocol: "Kujira",
      symbol: "sKUJI",
      name: "Staked KUJI",
      token: "terra188w26t95tf4dz77raftme8p75rggatxjxfeknw",
      icon: "https://assets.kujira.app/skuji.png",
      decimals: 6,
    },
    terra133chr09wu8sakfte5v7vd8qzq9vghtkv4tn0ur: {
      protocol: "Wormhole",
      symbol: "wstETH",
      name: "Lido wstETH (Portal)",
      token: "terra133chr09wu8sakfte5v7vd8qzq9vghtkv4tn0ur",
      icon: "https://static.lido.fi/wstETH/wstETH.png",
      decimals: 8,
    },
    terra1t9ul45l7m6jw6sxgvnp8e5hj8xzkjsg82g84ap: {
      protocol: "Wormhole",
      symbol: "wstSOL",
      name: "Lido wstSOL (Portal)",
      token: "terra1t9ul45l7m6jw6sxgvnp8e5hj8xzkjsg82g84ap",
      icon: "https://static.lido.fi/stSOL/stSOL.png",
      decimals: 8,
    },
    terra1c3xd5s2j3ejx2d94tvcjfkrdeu6rmz48ghzznj: {
      protocol: "Wormhole",
      symbol: "wsbSOL",
      name: "Lido bonded SOL (Portal)",
      token: "terra1c3xd5s2j3ejx2d94tvcjfkrdeu6rmz48ghzznj",
      icon: "https://raw.githubusercontent.com/ChorusOne/token-list/main/assets/mainnet/EbMg3VYAE9Krhndw7FuogpHNcEPkXVhtXr7mGisdeaur/logo.svg",
      decimals: 8,
    },
    terra1jxypgnfa07j6w92wazzyskhreq2ey2a5crgt6z: {
      protocol: "Wormhole",
      symbol: "LDO",
      name: "Lido DAO (Portal)",
      token: "terra1jxypgnfa07j6w92wazzyskhreq2ey2a5crgt6z",
      icon: "https://static.lido.fi/LDO/LDO.png",
      decimals: 8,
    },
    terra1u5szg038ur9kzuular3cae8hq6q5rk5u27tuvz: {
      protocol: "Wormhole",
      symbol: "webETH",
      name: "Lido Bonded ETH (Wormhole)",
      token: "terra1u5szg038ur9kzuular3cae8hq6q5rk5u27tuvz",
      icon: "https://static.lido.fi/bETH_Wormhole/bETH_Wormhole.svg",
      decimals: 8,
    },
    terra1yg3j2s986nyp5z7r2lvt0hx3r0lnd7kwvwwtsc: {
      protocol: "Lido",
      symbol: "stLuna",
      name: "Lido staked Luna",
      token: "terra1yg3j2s986nyp5z7r2lvt0hx3r0lnd7kwvwwtsc",
      icon: "https://static.lido.fi/stLUNA/stLUNA.png",
      decimals: 6,
    },
    terra169edevav3pdrtjcx35j6pvzuv54aevewar4nlh: {
      protocol: "Wormhole",
      symbol: "XDEFI",
      name: "XDEFI (Portal)",
      token: "terra169edevav3pdrtjcx35j6pvzuv54aevewar4nlh",
      icon: "https://github.com/sushiswap/assets/blob/master/blockchains/ethereum/assets/0x72B886d09C117654aB7dA13A14d603001dE0B777/logo.png?raw=true",
      decimals: 8,
    },
    terra193c42lfwmlkasvcw22l9qqzc5q2dx208tkd7wl: {
      protocol: "Bitlocus",
      symbol: "BTL",
      name: "Bitlocus Token",
      token: "terra193c42lfwmlkasvcw22l9qqzc5q2dx208tkd7wl",
      icon: "https://bitlocus.com/assets/btl-token.png",
      decimals: 6,
    },
    terra17y9qkl8dfkeg4py7n0g5407emqnemc3yqk5rup: {
      protocol: "Stader",
      symbol: "LunaX",
      name: "LunaX Token",
      token: "terra17y9qkl8dfkeg4py7n0g5407emqnemc3yqk5rup",
      icon: "https://raw.githubusercontent.com/stader-labs/assets/main/terra/LunaX_1.png",
      decimals: 6,
    },
    terra1m3tdguf59xq3pa2twk5fjte5g6szj5y9x5npy7: {
      protocol: "LUNI",
      symbol: "LUNI",
      name: "LUNI",
      token: "terra1m3tdguf59xq3pa2twk5fjte5g6szj5y9x5npy7",
      icon: "https://d2s3n99uw51hng.cloudfront.net/static/100_100_LUNI_logo.png",
      decimals: 6,
    },
    terra13awdgcx40tz5uygkgm79dytez3x87rpg4uhnvu: {
      protocol: "PlayNity",
      symbol: "PLY",
      name: "PlayNity Token",
      token: "terra13awdgcx40tz5uygkgm79dytez3x87rpg4uhnvu",
      icon: "https://playnity.io/uploads/logo/logo100.png",
      decimals: 6,
    },
    terra1u2k0nkenw0p25ljsr4ksh7rxm65y466vkdewwj: {
      protocol: "TerraFloki",
      symbol: "TFLOKI",
      name: "TFLOKI",
      token: "terra1u2k0nkenw0p25ljsr4ksh7rxm65y466vkdewwj",
      icon: "https://terrafloki.io/terrafloki_logo.png",
      decimals: 6,
    },
    terra1a8k3jyv3wf6k3zngza5h6srrxcckdf7zv90p6u: {
      protocol: "TerraFloki",
      symbol: "TFTIC",
      name: "TFLOKI Genesis Ticket",
      token: "terra1a8k3jyv3wf6k3zngza5h6srrxcckdf7zv90p6u",
      icon: "https://terrafloki.io/ticket_logo.png",
      decimals: 6,
    },
    terra1xt9fgu7965kgvunnjts9zkprd8986kcc444q86: {
      protocol: "TerraFloki",
      symbol: "TFTICII",
      name: "TFLOKI New World Ticket",
      token: "terra1xt9fgu7965kgvunnjts9zkprd8986kcc444q86",
      icon: "https://terrafloki.io/ticket2_logo.png",
      decimals: 6,
    },
    terra1vte2xv7dr8sfnrnwdf9arcyprqgr0hty5ads28: {
      protocol: "TerraFloki",
      symbol: "TFTICIII",
      name: "TFLOKI Aviator Ticket",
      token: "terra1vte2xv7dr8sfnrnwdf9arcyprqgr0hty5ads28",
      icon: "https://terrafloki.io/ticket3_logo.png",
      decimals: 6,
    },
    terra1hmxxq0y8h79f3228vs0czc4uz5jdgjt0appp26: {
      protocol: "Moon",
      symbol: "MOON",
      name: "Moon Token",
      token: "terra1hmxxq0y8h79f3228vs0czc4uz5jdgjt0appp26",
      icon: "https://moon.gl/logo.png",
    },
    terra1xj49zyqrwpv5k928jwfpfy2ha668nwdgkwlrg3: {
      protocol: "Astroport",
      symbol: "ASTROC",
      name: "Astroport Classic Token",
      token: "terra1xj49zyqrwpv5k928jwfpfy2ha668nwdgkwlrg3",
      icon: "https://astroport.fi/astro_logo.png",
      decimals: 6,
    },
    terra14lpnyzc9z4g3ugr4lhm8s4nle0tq8vcltkhzh7: {
      protocol: "Astroport",
      symbol: "xASTROC",
      name: "Staked Astroport Classic Token",
      token: "terra14lpnyzc9z4g3ugr4lhm8s4nle0tq8vcltkhzh7",
      icon: "https://app.astroport.fi/tokens/xAstro.png",
      decimals: 6,
    },
    terra1w8kvd6cqpsthupsk4l0clwnmek4l3zr7c84kwq: {
      protocol: "Angel Protocol",
      symbol: "HALO",
      name: "Angel Protocol Token",
      token: "terra1w8kvd6cqpsthupsk4l0clwnmek4l3zr7c84kwq",
      icon: "https://angelprotocol.io/favicon.png",
      decimals: 6,
    },
    terra1kdfsdm3c4reun9j3m4mk3nmyw4a4ns7mj24q3j: {
      protocol: "AstroPug",
      symbol: "PUG",
      name: "AstroPug Token",
      token: "terra1kdfsdm3c4reun9j3m4mk3nmyw4a4ns7mj24q3j",
      icon: "https://raw.githubusercontent.com/astropug/astropug-world/master/logo.png",
      decimals: 6,
    },
    terra1hnezwjqlhzawcrfysczcxs6xqxu2jawn729kkf: {
      protocol: "Orne",
      symbol: "ORNE",
      name: "Orne Token",
      token: "terra1hnezwjqlhzawcrfysczcxs6xqxu2jawn729kkf",
      icon: "https://orne.io/img/token_icon.png",
      decimals: 6,
    },
    terra14vz4v8adanzph278xyeggll4tfww7teh0xtw2y: {
      protocol: "Terra Name Service",
      symbol: "TNS",
      name: "Terra Name Service",
      token: "terra14vz4v8adanzph278xyeggll4tfww7teh0xtw2y",
      icon: "https://tns.money/static/images/tns.png",
      decimals: 6,
    },
    terra1td743l5k5cmfy7tqq202g7vkmdvq35q48u2jfm: {
      protocol: "Thorstarter",
      symbol: "XRUNE",
      name: "Thorstarter",
      token: "terra1td743l5k5cmfy7tqq202g7vkmdvq35q48u2jfm",
      icon: "https://thorstarter.org/static/img/src/favicon.png",
      decimals: 6,
    },
    terra1366wmr8t8rrkh6mag8fagqxntmf2qe4kyte784: {
      protocol: "LoT",
      symbol: "aLOT",
      name: "Alpha Pack Token",
      token: "terra1366wmr8t8rrkh6mag8fagqxntmf2qe4kyte784",
      icon: "https://ipfs.playlot.io/icon/profile-logo.png",
      decimals: 0,
    },
    terra1z09gnzufuflz6ckd9k0u456l9dnpgsynu0yyhe: {
      protocol: "Curio",
      symbol: "SITY",
      name: "CurioSITY play to earn token",
      token: "terra1z09gnzufuflz6ckd9k0u456l9dnpgsynu0yyhe",
      icon: "https://www.curio.art/img/logo.svg",
      decimals: 6,
    },
    terra13zx49nk8wjavedjzu8xkk95r3t0ta43c9ptul7: {
      protocol: "Glow",
      symbol: "GLOW",
      name: "Glow Token",
      token: "terra13zx49nk8wjavedjzu8xkk95r3t0ta43c9ptul7",
      icon: "https://glowyield.com/assets/img/icons/glow.png",
      decimals: 6,
    },
    terra100yeqvww74h4yaejj6h733thgcafdaukjtw397: {
      protocol: "Apollo",
      symbol: "APOLLO",
      name: "Apollo DAO Token",
      token: "terra100yeqvww74h4yaejj6h733thgcafdaukjtw397",
      icon: "https://finder.extraterrestrial.money/images/APOLLO60.png",
      decimals: 6,
    },
    terra1a7ye2splpfzyenu0yrdu8t83uzgusx2malkc7u: {
      protocol: "Allbridge",
      symbol: "ABR",
      name: "Allbridge",
      token: "terra1a7ye2splpfzyenu0yrdu8t83uzgusx2malkc7u",
      icon: "https://raw.githubusercontent.com/allbridge-io/media/main/token.svg",
      decimals: 6,
    },
    terra1y3d5qexmyac0fg53pfglh2pjk0664ymfvcq9mc: {
      protocol: "Wormhole",
      symbol: "whGTPS",
      name: "Global Transaction Payment Solu",
      token: "terra1y3d5qexmyac0fg53pfglh2pjk0664ymfvcq9mc",
      icon: "https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/32x32coinlogo.png?ver=1640952410118",
      decimals: 8,
    },
    terra1dh9478k2qvqhqeajhn75a2a7dsnf74y5ukregw: {
      protocol: "Prism",
      symbol: "PRISM",
      name: "Prism Protocol Token",
      token: "terra1dh9478k2qvqhqeajhn75a2a7dsnf74y5ukregw",
      icon: "https://prismprotocol.app/prism.png",
      decimals: 6,
    },
    terra1l0y8yg0s86x299nqw0p6fhh7ngex3r4phtjeuq: {
      protocol: "Space Dollar Society",
      symbol: "SDOLLAR",
      name: "Space Dollar",
      token: "terra1l0y8yg0s86x299nqw0p6fhh7ngex3r4phtjeuq",
      icon: "https://sdollars.wpengine.com/wp-content/uploads/2021/10/spacedollars512x512.png",
      decimals: 2,
    },
    terra1ku5e0dhutxhuxudsmsn5647wwcz6ndr3rsh90k: {
      protocol: "Wormhole",
      symbol: "whSAIL",
      name: "SAIL",
      token: "terra1ku5e0dhutxhuxudsmsn5647wwcz6ndr3rsh90k",
      icon: "https://cloudflare-ipfs.com/ipfs/QmPcQfofQNfiv36EAsGQrgAhiPbqGf17i1Cz648JhXFW9m/logo_solana_sail_v2.png",
      decimals: 6,
    },
    terra1rl0cpwgtwl4utnaynugevdje37fnmsea7rv4uu: {
      protocol: "Wormhole",
      symbol: "whgSAIL",
      name: "SolanaSail Governance Token V2",
      token: "terra1rl0cpwgtwl4utnaynugevdje37fnmsea7rv4uu",
      icon: "https://ipfs.io/ipfs/QmNNt1xoyB7gwjLLzUYMELYGY277ZzZXJw1vhnZW18Wozq?filename=logo_GSAIL.png",
      decimals: 8,
    },
    terra1042wzrwg2uk6jqxjm34ysqquyr9esdgm5qyswz: {
      protocol: "Prism",
      symbol: "xPRISM",
      name: "Prism Governance Token",
      token: "terra1042wzrwg2uk6jqxjm34ysqquyr9esdgm5qyswz",
      icon: "https://prismprotocol.app/xprism.png",
      decimals: 6,
    },
    terra13fs83g5atgjwuh7c5ydzh6n7gecel6xyhhy2t5: {
      protocol: "CAPITRADE",
      symbol: "CDE",
      name: "CAPITRADE TOKEN",
      token: "terra13fs83g5atgjwuh7c5ydzh6n7gecel6xyhhy2t5",
      icon: "https://raw.githubusercontent.com/Lotaxgizmo/images/57f862e3c2a68708775dae5f962885f2ed309b2d/ICON%20COLOURED%404x%201.png",
      decimals: 9,
    },
    terra1rl20t79ffsrqfa29rke48tj05gj9jxumm92vg8: {
      protocol: "C2X",
      symbol: "CTX",
      name: "C2X Token",
      token: "terra1rl20t79ffsrqfa29rke48tj05gj9jxumm92vg8",
      icon: "https://c2x.world/c2x-station/icon/C2X.png",
    },
    terra13zaagrrrxj47qjwczsczujlvnnntde7fdt0mau: {
      protocol: "Prism",
      symbol: "cLuna",
      name: "Prism cLuna Token",
      token: "terra13zaagrrrxj47qjwczsczujlvnnntde7fdt0mau",
      icon: "https://home.prismprotocol.app/cluna.png",
      decimals: 6,
    },
    terra1tlgelulz9pdkhls6uglfn5lmxarx7f2gxtdzh2: {
      protocol: "Prism",
      symbol: "pLuna",
      name: "Prism pLuna Token",
      token: "terra1tlgelulz9pdkhls6uglfn5lmxarx7f2gxtdzh2",
      icon: "https://home.prismprotocol.app/pluna.png",
      decimals: 6,
    },
    terra17wkadg0tah554r35x6wvff0y5s7ve8npcjfuhz: {
      protocol: "Prism",
      symbol: "yLuna",
      name: "Prism yLuna Token",
      token: "terra17wkadg0tah554r35x6wvff0y5s7ve8npcjfuhz",
      icon: "https://home.prismprotocol.app/yluna.png",
      decimals: 6,
    },
    terra1cl7whtrqmz5ldr553q69qahck8xvk80fm33qjx: {
      protocol: "Atlo",
      symbol: "ATLO",
      name: "Atlo Token",
      token: "terra1cl7whtrqmz5ldr553q69qahck8xvk80fm33qjx",
      icon: "https://assets.atlo.app/images/atlo-logo.png",
      decimals: 6,
    },
    terra1vchw83qt25j89zqwdpmdzj722sqxthnckqzxxp: {
      protocol: "Local Terra",
      symbol: "LOCAL",
      name: "LOCAL Token",
      token: "terra1vchw83qt25j89zqwdpmdzj722sqxthnckqzxxp",
      icon: "https://localterra.money/local-logo-dark.png",
      decimals: 6,
    },
    terra15k5r9r8dl8r7xlr29pry8a9w7sghehcnv5mgp6: {
      protocol: "Lunaverse",
      symbol: "LUV",
      name: "Lunaverse",
      token: "terra15k5r9r8dl8r7xlr29pry8a9w7sghehcnv5mgp6",
      icon: "https://lunaverse.io/assets/images/logo.png",
      decimals: 6,
    },
    terra1f62tqesptvmhtzr8sudru00gsdtdz24srgm7wp: {
      protocol: "Terra",
      symbol: "ROBO",
      name: "RoboHero",
      token: "terra1f62tqesptvmhtzr8sudru00gsdtdz24srgm7wp",
      icon: "https://robohero.io/assets/token.png",
      decimals: 6,
    },
    terra1vwz7t30q76s7xx6qgtxdqnu6vpr3ak3vw62ygk: {
      protocol: "Luart",
      symbol: "LUART",
      name: "Luart Token",
      token: "terra1vwz7t30q76s7xx6qgtxdqnu6vpr3ak3vw62ygk",
      icon: "https://cdn.luart.io/logos/luart-logo.png",
      decimals: 6,
    },
    terra12hgwnpupflfpuual532wgrxu2gjp0tcagzgx4n: {
      protocol: "Mars",
      symbol: "MARS",
      name: "Mars Token",
      token: "terra12hgwnpupflfpuual532wgrxu2gjp0tcagzgx4n",
      icon: "https://marsprotocol.io/MARSTokenMini.svg",
      decimals: 6,
    },
    terra1a04v570f9cxp49mk06vjsm8axsswndpwwt67k4: {
      protocol: "Mars",
      symbol: "XMARS",
      name: "xMars Token",
      token: "terra1a04v570f9cxp49mk06vjsm8axsswndpwwt67k4",
      icon: "https://marsprotocol.io/xMARSTokenMini.svg",
      decimals: 6,
    },
    terra1vpws4hmpmpsqwnz3gljn8zj42rv7rkpc5atgt4: {
      protocol: "Wormhole",
      symbol: "DFIAT",
      name: "DeFiato",
      token: "terra1vpws4hmpmpsqwnz3gljn8zj42rv7rkpc5atgt4",
      icon: "https://defiato-public.s3.ap-southeast-1.amazonaws.com/defiato-logo-small.jpeg",
      decimals: 8,
    },
    terra1hppnw4jppmrzzga4yvd8s87y3dwkhe27xwwl5d: {
      protocol: "Ceres",
      symbol: "CERES",
      name: "Ceres Governance Token",
      token: "terra1hppnw4jppmrzzga4yvd8s87y3dwkhe27xwwl5d",
      icon: "https://cloudflare-ipfs.com/ipfs/QmVeSBHDtJYFd6yKSdFghRRsj4jXHdm81rmCUEdLHDK928?filename=ceres.svg",
      decimals: 6,
    },
    terra1z3e2e4jpk4n0xzzwlkgcfvc95pc5ldq0xcny58: {
      protocol: "Wormhole",
      symbol: "wasAVAX",
      name: "BENQI Staked AVAX (Portal)",
      token: "terra1z3e2e4jpk4n0xzzwlkgcfvc95pc5ldq0xcny58",
      icon: "https://benqi.fi/images/assets/savax.svg",
      decimals: 8,
    },
    terra1zd6let0zg0xjn2sestagxv4ax24a4ml6j40qdr: {
      protocol: "MintDAO",
      symbol: "MINT",
      name: "MintDAO",
      token: "terra1zd6let0zg0xjn2sestagxv4ax24a4ml6j40qdr",
      icon: "https://mintdao.io/assets/token.svg",
      decimals: 6,
    },
    terra1ustvnmngueq0p4jd7gfnutgvdc6ujpsjhsjd02: {
      protocol: "Stader",
      symbol: "SD",
      name: "Stader SD (Portal)",
      token: "terra1ustvnmngueq0p4jd7gfnutgvdc6ujpsjhsjd02",
      icon: "https://raw.githubusercontent.com/stader-labs/assets/main/terra/whSD.png",
      decimals: 8,
    },
    terra1ln2z938phz0nc2wepxpzfkwp6ezn9yrz9zv9ep: {
      protocol: "Stader",
      symbol: "xSD",
      name: "Stader xSD",
      token: "terra1ln2z938phz0nc2wepxpzfkwp6ezn9yrz9zv9ep",
      icon: "https://raw.githubusercontent.com/stader-labs/assets/main/terra/xSD.png",
      decimals: 8,
    },
    terra1uux6gwd6pzr0gfzrru5kne55cxex9d0700c72r: {
      protocol: "Wormhole",
      symbol: "PAXG",
      name: "Paxos Gold (Portal)",
      token: "terra1uux6gwd6pzr0gfzrru5kne55cxex9d0700c72r",
      icon: "https://github.com/paxosglobal/paxos-gold-contract/blob/master/assets/Pax-Gold-Logo-FINAL-color.png?raw=true",
      decimals: 8,
    },
    terra1efjugpjc50d8sha7lr8s48cr7wmsthz94eevcl: {
      protocol: "Wormhole",
      symbol: "whDAO",
      name: "DAO Maker",
      token: "terra1efjugpjc50d8sha7lr8s48cr7wmsthz94eevcl",
      icon: "https://etherscan.io/token/images/daomaker_128.png",
      decimals: 8,
    },
    terra1su6g4t4vwx7y0uh3ksancyaurj4l6w9pfs40qt: {
      protocol: "Chainlink",
      symbol: "LINK",
      name: "ChainLink Token",
      token: "terra1su6g4t4vwx7y0uh3ksancyaurj4l6w9pfs40qt",
      icon: "https://ipfs.io/ipfs/QmbfnNALyHC3siaZR3j2mQ44MDVFr2dtR5ciqu3anbD4eP?filename=chainlink.png",
      decimals: 18,
    },
    terra14v9wrjs55qsn9lkvylsqela3w2ytwxzkycqzcr: {
      protocol: "Sayve",
      symbol: "SAYVE",
      name: "Sayve Token",
      token: "terra14v9wrjs55qsn9lkvylsqela3w2ytwxzkycqzcr",
      icon: "https://raw.githubusercontent.com/sayveprotocol/web-assets/main/logos/sayve-logo.png",
      decimals: 6,
    },
    terra1z55rhw0ut70jxdmpvge98mvj0rkwcz74q77z0u: {
      protocol: "Guides",
      symbol: "GUIDES",
      name: "Guides Token",
      token: "terra1z55rhw0ut70jxdmpvge98mvj0rkwcz74q77z0u",
      icon: "https://cdn.fs.guides.co/HBAKzovT2ulOa54snzDg",
      decimals: 6,
    },
    terra1mt2ytlrxhvd5c4d4fshxxs3zcus3fkdmuv4mk2: {
      protocol: "Brokkr Brotocol",
      symbol: "BRO",
      name: "BRO token",
      token: "terra1mt2ytlrxhvd5c4d4fshxxs3zcus3fkdmuv4mk2",
      icon: "https://brokkr.finance/static/BRO/Bro-Token-64.svg",
      decimals: 6,
    },
    terra1qryq5wreecx2wd3cdtzz94syr4z0a92l60asds: {
      protocol: "Brokkr Brotocol",
      symbol: "bBRO",
      name: "bBRO token",
      token: "terra1qryq5wreecx2wd3cdtzz94syr4z0a92l60asds",
      icon: "https://brokkr.finance/static/bBRO/bBro-Token-64.svg",
      decimals: 6,
    },
    terra15zvyhmv6gwddht7kt4q6w5nasn4tcpgzcdfmgr: {
      protocol: "Terra",
      symbol: "GTPS",
      name: "Global Transaction Payment Solut",
      token: "terra15zvyhmv6gwddht7kt4q6w5nasn4tcpgzcdfmgr",
      icon: "https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/225x225GTPS.png?ver=1649021019248",
      decimals: 18,
    },
    terra15pkdjxv2ewjzn9x665y26pfz2h6ymak4d4e8se: {
      protocol: "Terra",
      symbol: "GFI",
      name: "Gtps.Finance",
      token: "terra15pkdjxv2ewjzn9x665y26pfz2h6ymak4d4e8se",
      icon: "https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/GtpsFinance225x225.png?ver=1649021019248",
      decimals: 18,
    },
    terra1fyjsxx73jrufw8ufgtuswa773dvdkny92k70wa: {
      protocol: "Terra",
      symbol: "ULC",
      name: "Ultimatalioniscoin",
      token: "terra1fyjsxx73jrufw8ufgtuswa773dvdkny92k70wa",
      icon: "https://img1.wsimg.com/blobby/go/f561f953-0bdd-48bf-a39b-982ecbd1698b/downloads/Ultimatalioniscoin225x225.png?ver=1649021019249",
      decimals: 18,
    },
    terra1689ys6p6gfu0q6xrjqkzfn80sdyhurjqn0jfdl: {
      symbol: "SST",
      name: "Sooah Studio Token",
      token: "terra1689ys6p6gfu0q6xrjqkzfn80sdyhurjqn0jfdl",
      icon: "https://sooahphoto.co.kr/icon/logo.png",
      decimals: 6,
    },
    terra1rg8f993m9834afwazersesgx7jjxv4p87q9wvc: {
      protocol: "Wormhole",
      symbol: "ATLAS",
      name: "Star Atlas (Portal)",
      token: "terra1rg8f993m9834afwazersesgx7jjxv4p87q9wvc",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/ATLAS_wh.png",
      decimals: 8,
    },
    terra1nc6flp57m5hsr6y5y8aexzszy43ksr0drdr8rp: {
      protocol: "Wormhole",
      symbol: "AUDIO",
      name: "Audius (Portal)",
      token: "terra1nc6flp57m5hsr6y5y8aexzszy43ksr0drdr8rp",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/AUDIO_wh.png",
      decimals: 8,
    },
    terra1hj8de24c3yqvcsv9r8chr03fzwsak3hgd8gv3m: {
      protocol: "Wormhole",
      symbol: "AVAX",
      name: "AVAX (Portal)",
      token: "terra1hj8de24c3yqvcsv9r8chr03fzwsak3hgd8gv3m",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/AVAX_wh.png",
      decimals: 8,
    },
    terra1apxgj5agkkfdm2tprwvykug0qtahxvfmugnhx2: {
      protocol: "Wormhole",
      symbol: "BAT",
      name: "Basic Attention Token (Portal)",
      token: "terra1apxgj5agkkfdm2tprwvykug0qtahxvfmugnhx2",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/BAT_wh.png",
      decimals: 8,
    },
    terra1skjr69exm6v8zellgjpaa2emhwutrk5a6dz7dd: {
      protocol: "Wormhole",
      symbol: "BUSDbs",
      name: "Binance USD (Portal from BSC)",
      token: "terra1skjr69exm6v8zellgjpaa2emhwutrk5a6dz7dd",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/BUSDbs_wh.png",
      decimals: 8,
    },
    terra1zmclyfepfmqvfqflu8r3lv6f75trmg05z7xq95: {
      protocol: "Wormhole",
      symbol: "DAI",
      name: "DAI (Portal)",
      token: "terra1zmclyfepfmqvfqflu8r3lv6f75trmg05z7xq95",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/DAI_wh.png",
      decimals: 8,
    },
    terra1dtqlfecglk47yplfrtwjzyagkgcqqngd5lgjp8: {
      protocol: "Wormhole",
      symbol: "MATICpo",
      name: "MATIC (Portal from Polygon)",
      token: "terra1dtqlfecglk47yplfrtwjzyagkgcqqngd5lgjp8",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/MATICpo_wh.png",
      decimals: 8,
    },
    terra15a9dr3a2a2lj5fclrw35xxg9yuxg0d908wpf2y: {
      protocol: "Wormhole",
      symbol: "MIMet",
      name: "Magic Internet Money (Portal from Ethereum)",
      token: "terra15a9dr3a2a2lj5fclrw35xxg9yuxg0d908wpf2y",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/MIMet_wh.png",
      decimals: 8,
    },
    terra1ht5sepn28z999jx33sdduuxm9acthad507jg9q: {
      protocol: "Wormhole",
      symbol: "RAY",
      name: "Raydium (Portal)",
      token: "terra1ht5sepn28z999jx33sdduuxm9acthad507jg9q",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/RAY_wh.png",
      decimals: 6,
    },
    terra17h82zsq6q8x5tsgm5ugcx4gytw3axguvzt4pkc: {
      protocol: "Wormhole",
      symbol: "SBR",
      name: "Saber (Portal)",
      token: "terra17h82zsq6q8x5tsgm5ugcx4gytw3axguvzt4pkc",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/SBR_wh.png",
      decimals: 6,
    },
    terra1huku2lecfjhq9d00k5a8dh73gw7dwe6vvuf2dd: {
      protocol: "Wormhole",
      symbol: "SHIB",
      name: "Shiba Inu (Portal)",
      token: "terra1huku2lecfjhq9d00k5a8dh73gw7dwe6vvuf2dd",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/SHIB_wh.png",
      decimals: 8,
    },
    terra1dkam9wd5yvaswv4yq3n2aqd4wm5j8n82qc0c7c: {
      protocol: "Wormhole",
      symbol: "SRMso",
      name: "Serum (Portal from Solana)",
      token: "terra1dkam9wd5yvaswv4yq3n2aqd4wm5j8n82qc0c7c",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/SRMso_wh.png",
      decimals: 6,
    },
    terra1pvel56a2hs93yd429pzv9zp5aptcjg5ulhkz7w: {
      protocol: "Wormhole",
      symbol: "USDCav",
      name: "USD Coin (Portal from Avalanche)",
      token: "terra1pvel56a2hs93yd429pzv9zp5aptcjg5ulhkz7w",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDCav_wh.png",
      decimals: 6,
    },
    terra1yljlrxvkar0c6ujpvf8g57m5rpcwl7r032zyvu: {
      protocol: "Wormhole",
      symbol: "USDCbs",
      name: "USD Coin (Portal from BSC)",
      token: "terra1yljlrxvkar0c6ujpvf8g57m5rpcwl7r032zyvu",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDCbs_wh.png",
      decimals: 8,
    },
    terra1kkyyh7vganlpkj0gkc2rfmhy858ma4rtwywe3x: {
      protocol: "Wormhole",
      symbol: "USDCpo",
      name: "USD Coin (Portal from Polygon)",
      token: "terra1kkyyh7vganlpkj0gkc2rfmhy858ma4rtwywe3x",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDCpo_wh.png",
      decimals: 6,
    },
    terra1e6mq63y64zcxz8xyu5van4tgkhemj3r86yvgu4: {
      protocol: "Wormhole",
      symbol: "USDCso",
      name: "USD Coin (Portal from Solana)",
      token: "terra1e6mq63y64zcxz8xyu5van4tgkhemj3r86yvgu4",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDCso_wh.png",
      decimals: 6,
    },
    terra1eqvq3thjhye7anv6f6mhxpjhyvww8zjvqcdgjx: {
      protocol: "Wormhole",
      symbol: "USDTav",
      name: "Tether USD (Portal from Avalanche)",
      token: "terra1eqvq3thjhye7anv6f6mhxpjhyvww8zjvqcdgjx",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDTav_wh.png",
      decimals: 6,
    },
    terra1vlqeghv5mt5udh96kt5zxlh2wkh8q4kewkr0dd: {
      protocol: "Wormhole",
      symbol: "USDTbs",
      name: "Tether USD (Portal from BSC)",
      token: "terra1vlqeghv5mt5udh96kt5zxlh2wkh8q4kewkr0dd",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDTbs_wh.png",
      decimals: 8,
    },
    terra1hd9n65snaluvf7en0p4hqzse9eqecejz2k8rl5: {
      protocol: "Wormhole",
      symbol: "USDTso",
      name: "Tether USD (Portal from Solana)",
      token: "terra1hd9n65snaluvf7en0p4hqzse9eqecejz2k8rl5",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/USDTso_wh.png",
      decimals: 6,
    },
    terra1fpfn2kkr8mv390wx4dtpfk3vkjx9ch3thvykl3: {
      protocol: "Wormhole",
      symbol: "gOHM",
      name: "Governance OHM (Portal)",
      token: "terra1fpfn2kkr8mv390wx4dtpfk3vkjx9ch3thvykl3",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/gOHM_wh.png",
      decimals: 8,
    },
    terra1qvlpf2v0zmru3gtex40sqq02wxp39x3cjh359y: {
      protocol: "Wormhole",
      symbol: "mSOL",
      name: "Marinade staked SOL (Portal)",
      token: "terra1qvlpf2v0zmru3gtex40sqq02wxp39x3cjh359y",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/mSOL_wh.png",
      decimals: 8,
    },
    terra1w7ywr6waxtjuvn5svk5wqydqpjj0q9ps7qct4d: {
      protocol: "Wormhole",
      symbol: "stETH",
      name: "Lido Staked Ether (Portal)",
      token: "terra1w7ywr6waxtjuvn5svk5wqydqpjj0q9ps7qct4d",
      icon: "https://raw.githubusercontent.com/certusone/wormhole-token-list/main/assets/stETH_wh.png",
      decimals: 8,
    },
    terra1srp2u95kxps35nvan88gn96nfqhukqya2d0ffc: {
      protocol: "C2X",
      symbol: "LCT",
      name: "LCT Token",
      token: "terra1srp2u95kxps35nvan88gn96nfqhukqya2d0ffc",
      icon: "https://c2x.world/c2x-station/icon/LCT.png",
    },
    terra18zqcnl83z98tf6lly37gghm7238k7lh79u4z9a: {
      protocol: "Anchor",
      symbol: "bATOM",
      name: "Bonded ATOM",
      token: "terra18zqcnl83z98tf6lly37gghm7238k7lh79u4z9a",
      icon: "https://files.pstake.finance/logos/bAssets/bATOM.svg",
      decimals: 6,
    },
    terra128pe5jpempxu0nws5lw28se9zknhsr78626cpn: {
      protocol: "Wormhole",
      symbol: "webATOM",
      name: "pStake Bonded ATOM (Wormhole)",
      token: "terra128pe5jpempxu0nws5lw28se9zknhsr78626cpn",
      icon: "https://files.pstake.finance/logos/bAssets/bATOM_Wormhole.svg",
      decimals: 6,
    },
    terra1laczhlpxlgmrwr9un9ds74qxd2fj4754nf82dn: {
      protocol: "Willisch finance",
      symbol: "WCOIN",
      name: "Willisch Coin",
      token: "terra1laczhlpxlgmrwr9un9ds74qxd2fj4754nf82dn",
      icon: "https://www.willisch.finance/images/icons/wcoin.svg",
      decimals: 6,
    },
    terra1thhm2u93m2stytzynhsxh5h3jrtg540x4punqy: {
      protocol: "C2X",
      symbol: "LCTfancard",
      name: "LCT Fancard Token",
      token: "terra1thhm2u93m2stytzynhsxh5h3jrtg540x4punqy",
      icon: "https://c2x.world/c2x-station/icon/LCTfancard.png",
      decimals: 0,
    },
    terra1yeyr6taynkwdl85ppaggr3zr8txhf66cny2ang: {
      protocol: "Kinetic Money",
      symbol: "KNTC",
      name: "Kinetic Token",
      token: "terra1yeyr6taynkwdl85ppaggr3zr8txhf66cny2ang",
      icon: "https://app.kinetic.money/static/media/logo-kinetic.8c7f1942.svg",
      decimals: 6,
    },
    terra1g53pyke8jtmt4lwvk4yl0xaqc4u0qlsl8dz3ex: {
      protocol: "Kinetic Money",
      symbol: "kUST",
      name: "Kinetic kUST Token",
      token: "terra1g53pyke8jtmt4lwvk4yl0xaqc4u0qlsl8dz3ex",
      icon: "https://extraterra-assets.s3.us-east-2.amazonaws.com/images/SVG/kUST.svg",
      decimals: 6,
    },
    terra1rl4zyexjphwgx6v3ytyljkkc4mrje2pyznaclv: {
      protocol: "Steak",
      symbol: "STEAK",
      name: "Steak Token",
      token: "terra1rl4zyexjphwgx6v3ytyljkkc4mrje2pyznaclv",
      icon: "https://larry.engineer/assets/steak.svg",
      decimals: 6,
    },
    terra1jkkt5638cd5pur0u5jnr2juw0v6hz5d6z8xu8m: {
      protocol: "C2X",
      symbol: "CST",
      name: "CST Token",
      token: "terra1jkkt5638cd5pur0u5jnr2juw0v6hz5d6z8xu8m",
      icon: "https://c2x.world/c2x-station/icon/CST.png",
      decimals: 6,
    },
    terra1kz7qszu7p4dg9lts7m9m7lpuarsnan47jh3fam: {
      protocol: "C2X",
      symbol: "CSTfancard",
      name: "CST Fancard Token",
      token: "terra1kz7qszu7p4dg9lts7m9m7lpuarsnan47jh3fam",
      icon: "https://c2x.world/c2x-station/icon/CSTfancard.png",
      decimals: 0,
    },
    terra1amz5c45l34n7w8m5a3z7rd7u0k037x4nnsemwj: {
      protocol: "Neworld",
      symbol: "NWLD",
      name: "Neworld Labs Develpper Token",
      token: "terra1amz5c45l34n7w8m5a3z7rd7u0k037x4nnsemwj",
      icon: "https://raw.githubusercontent.com/neworld-labs/token-list/master/assets/TestNet/neworld-labs.png",
      decimals: 9,
    },
    terra1cdc6nlsx0l6jmt3nnx7gxjggf902wge3n2z76k: {
      protocol: "Fanfury",
      symbol: "FURY",
      name: "FURY",
      token: "terra1cdc6nlsx0l6jmt3nnx7gxjggf902wge3n2z76k",
      icon: "https://crytpo11.s3.eu-central-1.amazonaws.com/FANFURY_logo.png",
      decimals: 6,
    },
    terra17n223dxpkypc5c48la7aqjvverczg82ga3cr93: {
      protocol: "Reactor Money",
      symbol: "RCT",
      name: "Reactor Token",
      token: "terra17n223dxpkypc5c48la7aqjvverczg82ga3cr93",
      icon: "https://reactor.money/assets/logo.svg",
      decimals: 6,
    },
    terra14vw4sfqwe7jw8ppcc7u44vq7hy9qa2nlstnxmu: {
      protocol: "Vite",
      symbol: "VITC",
      name: "Vitamin Coin",
      token: "terra14vw4sfqwe7jw8ppcc7u44vq7hy9qa2nlstnxmu",
      icon: "https://raw.githubusercontent.com/vitelabs/crypto-info/master/tokens/vitc/tti_22d0b205bed4d268a05dfc3c.png",
      decimals: 6,
    },
    terra1948uvsah8aw40dhsa9mhl3htq8lraj0smlh77g: {
      protocol: "Wormhole",
      symbol: "SB",
      name: "DragonSB",
      token: "terra1948uvsah8aw40dhsa9mhl3htq8lraj0smlh77g",
      icon: "https://dragonsb.finance/img/image2/SB.png",
      decimals: 6,
    },
    terra1rz964297kvt86rteajhtp4hsffhcum0ye8eljh: {
      protocol: "R.E.S.Toads",
      symbol: "TOAD",
      name: "RESToad Token",
      token: "terra1rz964297kvt86rteajhtp4hsffhcum0ye8eljh",
      icon: "https://www.redeyedspacetoads.io/toad_token_logo.svg",
      decimals: 6,
    },
    terra1yhlhrea3rgyx2xdnsswsfakn28qa8z7yp5gmhd: {
      protocol: "Orion Money",
      symbol: "orionASTRO",
      name: "Orion Money xASTRO Derivative Token",
      token: "terra1yhlhrea3rgyx2xdnsswsfakn28qa8z7yp5gmhd",
      icon: "https://orion.money/assets/orionASTRO-LOGO@256x256.png",
      decimals: 6,
    },
    terra1j4hwavavmtsafa6zr0npalfz3tk9gf3p4787mp: {
      protocol: "Retrograde",
      symbol: "RETRO",
      name: "Retrograde",
      token: "terra1j4hwavavmtsafa6zr0npalfz3tk9gf3p4787mp",
      icon: "https://retrograde.money/retro_logo.png",
      decimals: 6,
    },
    terra16wggm67a34msdxasg2vergm2pt289y7930wv7d: {
      protocol: "TerrnadoCash",
      symbol: "TND",
      name: "TerrnadoCash",
      token: "terra16wggm67a34msdxasg2vergm2pt289y7930wv7d",
      icon: "https://terrnado.cash/logo.png",
      decimals: 6,
    },
    terra1n9k2he20h5vpyn4mgv7pg4pzvw2n3wc4a86v3g: {
      protocol: "TerrnadoCash",
      symbol: "sTND",
      name: "TerrnadoCash",
      token: "terra1n9k2he20h5vpyn4mgv7pg4pzvw2n3wc4a86v3g",
      icon: "https://terrnado.cash/stnd_logo.svg",
      decimals: 6,
    },
    terra1ezz5xply2v3xdyv32gy5tcd7zq4k235q4xtzwe: {
      protocol: "Neworld",
      symbol: "NWT",
      name: "Neworld Token",
      token: "terra1ezz5xply2v3xdyv32gy5tcd7zq4k235q4xtzwe",
      icon: "https://raw.githubusercontent.com/neworld-labs/token-list/master/assets/MainNet/NWT.png",
      decimals: 9,
    },
    terra1mpq5zkkm39nmjrjg9raknpfrfmcfwv0nh0whvn: {
      protocol: "Nebula",
      symbol: "NEB",
      token: "terra1mpq5zkkm39nmjrjg9raknpfrfmcfwv0nh0whvn",
      icon: "https://assets.neb.money/icons/NEB.png",
    },
    terra1c00vskhyzdv0z63z2tyetzx2qma67n2z3vzyn0: {
      protocol: "Anchor",
      symbol: "bSOL",
      name: "Bonded SOL",
      token: "terra1c00vskhyzdv0z63z2tyetzx2qma67n2z3vzyn0",
      icon: "https://raw.githubusercontent.com/ChorusOne/token-list/main/assets/mainnet/EbMg3VYAE9Krhndw7FuogpHNcEPkXVhtXr7mGisdeaur/logo.svg",
      decimals: 6,
    },
    terra16gqgpuy7z64chzz3su2xugjgrhuj3h89wx2z59: {
      protocol: "C2X",
      symbol: "BST",
      name: "BST Token",
      token: "terra16gqgpuy7z64chzz3su2xugjgrhuj3h89wx2z59",
      icon: "https://c2x.world/c2x-station/icon/BST.png",
    },
    terra1l670q2m9j3npltmsqe428mwu0msw336m8jtq00: {
      protocol: "C2X",
      symbol: "KRX",
      name: "KRX Token",
      token: "terra1l670q2m9j3npltmsqe428mwu0msw336m8jtq00",
      icon: "https://c2x.world/c2x-station/icon/KRX.png",
    },
    terra1fy7lnlls8ufzfeefc98tkn66x07scud2s3d23p: {
      protocol: "C2X",
      symbol: "BSTfancard",
      name: "BST Fancard Token",
      token: "terra1fy7lnlls8ufzfeefc98tkn66x07scud2s3d23p",
      icon: "https://c2x.world/c2x-station/icon/BSTfancard.png",
      decimals: 0,
    },
    terra1f5m40hs40sa9nuku776swjljsa2t39h58uhlw3: {
      protocol: "C2X",
      symbol: "KRXfancard",
      name: "KRX Fancard Token",
      token: "terra1f5m40hs40sa9nuku776swjljsa2t39h58uhlw3",
      icon: "https://c2x.world/c2x-station/icon/KRXfancard.png",
      decimals: 0,
    },
    terra1zjhsuvuy5z7ucvx56facefmlrrgluhun27chlf: {
      protocol: "C2X",
      symbol: "ILT",
      name: "ILT Token",
      token: "terra1zjhsuvuy5z7ucvx56facefmlrrgluhun27chlf",
      icon: "https://c2x.world/c2x-station/icon/ILT.png",
    },
    terra14s8p2wnvh5vpxn4fgu562m2sm9780pk5gvkf9a: {
      protocol: "C2X",
      symbol: "ILTfancard",
      name: "ILT Fancard Token",
      token: "terra14s8p2wnvh5vpxn4fgu562m2sm9780pk5gvkf9a",
      icon: "https://c2x.world/c2x-station/icon/ILTfancard.png",
      decimals: 0,
    },
    terra1kn85pdmrhhk2upjj8hf97lx3w3jg6gyzasyksp: {
      protocol: "Lira",
      symbol: "LIRA",
      name: "Lira Token",
      token: "terra1kn85pdmrhhk2upjj8hf97lx3w3jg6gyzasyksp",
      icon: "https://lira.financial/images/icons/lira.svg",
      decimals: 6,
    },
    terra1rjf3c4ayvx2d6pej6fanjhe54a2ds8dlh9f69s: {
      protocol: "Pepon",
      symbol: "PEPON",
      name: "PEPSON TOKEN",
      token: "terra1rjf3c4ayvx2d6pej6fanjhe54a2ds8dlh9f69s",
      icon: "https://raw.githubusercontent.com/panpepson/LWLC-crypto/master/terra-pepon/Pepon.png",
      decimals: 3,
    },
    terra102cjx95xvww7cl9l6usxltk75ww3mpxtyw4lpm: {
      protocol: "Tuna",
      symbol: "TUNA",
      name: "Tuna Money",
      token: "terra102cjx95xvww7cl9l6usxltk75ww3mpxtyw4lpm",
      icon: "https://tuna.money/content/images/2022/06/icon-2.png",
      decimals: 6,
    },
    terra13eekqp0zgj55arjuacpxqxzgqy2uydf5wzzqns9ddgpepj377afqflunf3: {
      protocol: "Prism",
      symbol: "cLUNA",
      name: "cLUNA",
      token: "terra13eekqp0zgj55arjuacpxqxzgqy2uydf5wzzqns9ddgpepj377afqflunf3",
      icon: "https://prismprotocol.app/cLuna.svg",
      decimals: 6
    },
    terra1hjyl8ymsd9sn59kx733aka4rxfelf43pw6fjjf: {
      protocol: "INTERCHAIN DAO COIN",
      symbol: "IDC",
      name: "INTERCHAIN DAO COIN",
      token: "terra1hjyl8ymsd9sn59kx733aka4rxfelf43pw6fjjf",
      icon: "https://gateway.pinata.cloud/ipfs/bafybeifpwyro73qvpsg2xulgqgkvrfbw5jtqxrkzsryq6kl3f4o23ohai4/IDC.png",
      decimals: 6,
    },
    terra1wvk6r3pmj0835udwns4r5e0twsclvcyuq9ucgm: {
      protocol: "Eris Protocol",
      symbol: "ampLUNC",
      name: "Amplified LUNC",
      token: "terra1wvk6r3pmj0835udwns4r5e0twsclvcyuq9ucgm",
      icon: "https://www.erisprotocol.com/assets/ampLunc100.png",
      decimals: 6,
    },
      terra10xp0alk5jh0sksynx7vt9jkelgdxdfzs4979tk: {
      protocol: "Wormhole",
      symbol: "JEFE",
      name: "JEFE TOKEN",
      token: "terra10xp0alk5jh0sksynx7vt9jkelgdxdfzs4979tk",
      icon: "https://s2.coinmarketcap.com/static/img/coins/64x64/16800.png",
      decimals: 8,
    },
    terra1vsyyg4rs483uzd7jzw5fqqlm2q5n2yd37yylfc: {
      protocol: "BAZ",
      symbol: "BAZ",
      name: "BAZ",
      token: "terra1vsyyg4rs483uzd7jzw5fqqlm2q5n2yd37yylfc",
      icon: "https://raw.githubusercontent.com/BAZustc/BAZ-CORE/main/BAZ.png",
      decimals: 6,
    },
    terra1pkp0pkxp9mtlan7cg0qatu65hmkgyq2342g27g: {
      protocol: "Lunar Deity",
      symbol: "DUST",
      name: "Moon Dust",
      token: "terra1pkp0pkxp9mtlan7cg0qatu65hmkgyq2342g27g",
      icon: "https://gateway.pinata.cloud/ipfs/QmQ4gGYkPE6MFGbCpamgdeG1aTeagjhAHcX1eszYzCjzvy",
      decimals: 6,
    },
     terra1kqf8ua7al5tdnkz95ue4zkuv4gcu52pt63ya54: {
      protocol: "Optimizer Protocol",
      symbol: "OPZC",
      name: "Lunc optimizer token",
      token: "terra1kqf8ua7al5tdnkz95ue4zkuv4gcu52pt63ya54",
      icon: "https://assets.terra.money/icon/opz/OPZ.png",
      decimals: 6,
    },
  },
  testnet: {
    terra1ss9zz4873vk4dd8dvua0vm83m6s8k7ctwp9efac0arytn6jthfgsy2d4a9: {
      protocol: "YFD",
      symbol: "YFD",
      name: "Y-Foundry DAO",
      token: "terra1293l9rgqk5vxndaeqmengssg3pdch57qpepgslh7p2sg3lqd87rss8du4s",
      icon: "https://raw.githubusercontent.com/Y-Foundry-Dao/brand-assets/main/contract/pisco-1/cw20-yfd.svg",
      decimals: 6
    }
  },
};
